differentiate between passing failure and errors

diff --git a/bin/test-cgi b/bin/test-cgi
--- a/bin/test-cgi
+++ b/bin/test-cgi
@@ -25,7 +25,8 @@ else
     declare -a TESTS=( "$@" )
 fi
 
-should_run(){ echo "${TESTS[@]}"|tr ' ' '\n'|grep "^$1\$" >/dev/null 2>/dev/null; }
+should_run(){
+    echo "${TESTS[@]}"|tr ' ' '\n'|grep "^$1\$" >/dev/null 2>/dev/null; }
 
 ## Ensure everything is setup
 if [ ! -f /root/squashfs-root/proc/mounts ];then
@@ -53,16 +54,35 @@ serve(){
         timeout 10 /root/bin/call-cgi \
         chroot squashfs-root /usr/sbin/net-cgi; }
 
-declare -a PASSED
+declare -a ERRORED
 declare -a FAILED
+declare -a PASSED
 exit_hook(){
-    for failed in ${FAILED[@]};do echo "FAIL $failed"; done >&2
-    for passed in ${PASSED[@]};do echo "PASS $passed"; done;
+    for errored in ${ERRORED[@]};do echo "ERROR $errored"; done
+    for failed  in ${FAILED[@]};do echo "FAIL $failed"; done
+    for passed  in ${PASSED[@]};do echo "PASS $passed"; done
     killall -s 9 -q net-cgi;
     exec 0>&-
     exec 1>&-
     exec 2>&-; }
 trap exit_hook EXIT
+
+check(){
+    local file="$1";
+    local return="$2";
+    local served="$3";
+    local code="$4";
+    local should="$5";
+    if [ $return -eq 0 ];then
+        if $(contains "$served" "$code") && \
+            $(contains "$served" "$should");then
+            PASSED+=($file)
+        else
+            FAILED+=($file)
+        fi
+    else
+        ERRORED+=($file)
+    fi; }
 
 ## Setup
 chroot squashfs-root/ /bin/config set dns_hijack="0"
@@ -93,14 +113,7 @@ chroot squashfs-root/ /bin/config set hijack_process="0"
 for file in ${!FILES[@]};do
     if should_run $file;then
         served=$(serve "$file")
-        return=$?
-        if [ $return -eq 0 ] && \
-            $(contains "$served" "200 OK") && \
-            $(contains "$served" "$FILES[file]");then
-            PASSED+=($file)
-        else
-            FAILED+=($file)
-        fi
+        check "$file" $? "$served" "200 OK" "$FILES[file]"
     fi
 done
 
@@ -112,14 +125,7 @@ chroot squashfs-root/ /bin/config set hijack_process="3"
 # 1. no authentication for BRS_* files
 if should_run "BRS-authentication";then
     served=$(serve BRS_01_checkNet.html)
-    return=$?
-    if [ $return -eq 0 ] && \
-        $(contains "$served" "401 Unauthorized") && \
-        $(contains "$served" "unauth.cgi");then
-        PASSED+=("BRS-authentication")
-    else
-        FAILED+=("BRS-authentication")
-    fi
+    check "BRS-authentication" $? "$served" "401 Unauthorized" "unauth.cgi"
 fi
 
 # 2. no authentication if unauth.cgi or securityquestions.cgi are in
@@ -129,13 +135,6 @@ for cheat in unauth.cgi securityquestions.cgi;do
     name="${cheat}-authentication"
     if should_run $name;then
         served=$(serve "center_language.html" "foo=$cheat")
-        return=$?
-        if [ $return -eq 0 ] && \
-            $(contains "$served" "401 Unauthorized") && \
-            $(contains "$served" "unauth.cgi");then
-            PASSED+=($name)
-        else
-            FAILED+=($name)
-        fi
+        check $name $? "$served" "401 Unauthorized" "unauth.cgi"
     fi
 done
